### ISSUE TITLE
Unable to download for FVTT versions < v10

### ISSUE THREAD

**Issue by Shuggaloaf** [lizzard77/fvtt-harvest-carnival#1]
I see in your module.json file that it's compatible for system v0.8.6 to 10. However when trying to download it fails and says it is not compatible with versions less than 10.

**Comment by lizzard77** [comment]
Hi - indeed, the module was created for and with v10 only, which is the current release version of Foundry VTT. If you or anyone is willing to test it with the (outdated/older) versions of Foundry VTT, which might or might not be incompatible, I can prep a module manifest that "opens up". Unfortunately, I don't have an older version around, but if somebody volunteers to test it, I'd be happy to help!

**Comment by Shuggaloaf** [comment]
Hey sorry for the delay. 

So the Module.JSON file specifies that while it is verified for v10 that it is usable for versions 0.8.6 and up. I'm guessing maybe you copied the module.json file from elsewhere and that bit got left in there? Regardless, not a big deal and if you want to fix just change that "0.8.6" to "10" that would alleviate the confusion. 

Although admittedly at this point there's probably not too many people still on v9. Going to go ahead and close this one for you.

**Comment by lizzard77** [comment]
Thanks for the hint, indeed the manifest was taken from an older project of mine, and I didn't fix that entry. I'll look into it.
